### PR TITLE
Functional tests for pulling xml files

### LINKED ISSUE #594: .ci functional tests for XML adapter pull
#### Definition of the test :

A set of functional tests will be created that will test the XML adapter's `Pull` action. These tests will replicate the tests done in the current XML toolkit pull test procedure, as well as adding any other valid tests not already reflected in the test procedures.
- Test pulling EnergyPlus
- Test pulling BlueBeam
- Test pulling GBXML
    - Test each type including null
- Test default pull case with BlueBeam xml file.

XML test files will be created and used to test the above.

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #594

 
Functional tests for the the pull action have been created that test a number of scenarios:
- Pulling BlueBeam markup xml
- Pulling EnergyPlus loads xml
- Pulling BHoM environment objects from GBXML
    - comparing panels pulled to the JSON test model, and checking that the correct number of objects was pulled
- Pulling with an undefined schema using BluebeamMarkup.xml

 ### Test files

 ### Changelog

 ### Additional comments

There are JSON files with the models that contain the serialised BHoM objects used to create the GBXML file.

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance
@BHoMBot check unit-tests

**Comment by Tom-Kingstone** [comment]
@BHoMBot check project-compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check unit-tests
@BHoMBot check required

**Comment by Tom-Kingstone** [comment]
@BHoMBot check required

**Comment by Tom-Kingstone** [comment]
@BHoMBot check copyright-compliance

**Review by FraserGreenroyd — APPROVED** [review]
Reviewed code, tests run through with @Tom-Kingstone, happy to merge, great work @Tom-Kingstone

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
