### PR TITLE
XML_Toolkit: updates to materials

### LINKED ISSUE #273: XML_Toolkit: Align with material changes
Align to changes made in https://github.com/BHoM/BHoM/pull/490 and https://github.com/BHoM/BHoM_Engine/pull/976

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### NOTE: Depends on 
https://github.com/BHoM/BHoM/pull/490
https://github.com/BHoM/BHoM_Engine/pull/976

 ### Issues addressed by this PR
Fixes #273 

 ### Test files
Existing test scripts

 ### Changelog
#### Changed
 - Changed material access properties to reflect changes in oM and engine

 ### Additional comments
Part of a wider merge, please do not merge without clearance! :smile:

### CODE REVIEW

**Comment by michaldengusiak** [comment]
I return to master and works fine
image

**Comment by FraserGreenroyd** [comment]
I have identified the problem is most likely to be in your build. You need to build the pulling toolkit (in this case most likely the Revit Toolkit) correctly. Make sure you have built Revit using Debug-Version year (e.g. 2018 not 2019) and rerun the test.

**Comment by FraserGreenroyd** [comment]
Again, I couldn't replicate your issue @mariatjader , I suspect it comes down to how you and @michaldengusiak have built your Revit Toolkits. I'm glad it worked on the TAS side though :smile:

**Comment by FraserGreenroyd** [comment]
I have removed the `do-not-merge` label as this PR and all related PRs are now ready for merging.

**Pull request merged**
