### PR TITLE
Fix bug in generic read

### LINKED ISSUE #549: Fail reading Generic XML
#### Description:

[Test procedure](https://burohappold.sharepoint.com/:w:/r/sites/BHoM/01_Master%20File/09_QAQC/04%20-%20Testing%20Procedures/0006_Foundational/0006_Foundational%20-%20XML%20Toolkit.docx?d=w4098bad6b285460ea66d0dbc3bff5246&csf=1&web=1&e=VIZzzw) for pulling generic XML fails, giving the following error

1. This component failed to run properly.
- Error: Data at the root level is invalid. Line 1, position 1.
- Occured in  BH.Adapter.XML.XMLAdapter.ReadDefault(Type type, XMLConfig config)
     called from BH.Adapter.XML.XMLAdapter.IRead(Type type, IList indices, ActionConfig actionConfig)
- Are you sure you have the correct type of inputs? Check their description for more details.

#### Steps to reproduce:

Run the script outlined in the test procedure

#### Test file(s):

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/03_Alpha/BHoM/XML_Toolkit?csf=1&web=1&e=IKrTF1

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #549 

 ### Test files
See issue and test procedure relating to pulling generic XML, rather than a defined schema.

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation

**Review by IsakNaslundBh — COMMENTED** [review]
Test procedure for Generic XML read is now passing.

Would like @jamesramsden-bh or @tg359 to test this before merge though and approve on their end to ensure this does not have any degrading effect on an BEnv workflows.

**Review by jamesramsden-bh — APPROVED** [review]
Tested against PullGeneric test file, no errors returned.

**Pull request merged**
