### PR TITLE
Move schema objects to the Adapter

### LINKED ISSUE #445: XML_oM: Inconsistent namespace update
#### Description:
In the code, the namespace have been updated to `BH.oM.External.XML.GBXML` but in `Versioning_32.json`, it was updated to `BH.oM.External.XML`. 

This means upgrade of types is currently failing. This is especially a big deal for components using the auto generated constructor as they store the type when saved.

### LINKED ISSUE #446: XML_oM: Name property overridden incorrectly
#### Description:
 Some `GBXMLObject` are overriding their `Name` property. Unfortunately, it is done incorrectly, causing serialisation of those objects to fail.
Two things are needed to fix this:
- The `Name` property of `GBXMLObject` should be declared `virtual` so it can be overridden. All properties should now be `virtual` everywhere anyway.
- All children of that class should use the keyword `override` instead of `new` on the `Name` property.

#### Steps to reproduce:
You can see that this is failing by creating a `DummyObject` of that type and trying to serialise it using `ToJson`

#### Expected behaviour:
Serialisation should work once the fix suggested above has been implemented.

### Additional comments
Honestly the XML_oM classes could use a bit of TLC:
- an empty line between each property
- the usual comment delimiters
- descriptions

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #446 
Fixes #445

 ### Test files

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@adecler have made the changes we discussed during the call and moved all oM objects up to the adapter level where they only serve a purpose for the gbXML schema :smile:

@MajaLindroth if you can review and make sure functionality is not broken from the move that'd be great!

**Comment by FraserGreenroyd** [comment]
@adecler I have also added that this PR fixes #445 following our discussion as well cause that answers the query I had, and should remove the double namespace moving which wasn't captured by `Versioning_32.json` for the oM

**Comment by FraserGreenroyd** [comment]
@rolyhudson tagging you for review as an FYI as the change here might impact how you're planning to do the KML stuff

**Comment by adecler** [comment]
@FraserGreenroyd , two things I have noticed so far:
- It's probably better to not have GBXMLObject as a BHoMObject to avoid confusing the reflection and serialisation engine.
- I wonder if the `External` namespace still makes sense anywhere in this repo. We are never creating object defined in a dlls external to the BHoM so I don't see where this would apply.

**Comment by al-fisher** [comment]
> I wonder if the External namespace still makes sense anywhere in this repo. We are never creating object defined in a dlls external to the BHoM so I don't see where this would apply.

On one of @adecler's points above 
I think this should be in `External` as this repo is solely about converting from BHoM to another schema. 
I think the `External` namespace should be used for these cases - to keep "converting and adapting" all in one place. And help keep the numbers of namespaces both focused and organised and navigable for describing discrete oM domains and disciplines  
Does that make sense to others?
😄

**Comment by adecler** [comment]
@al-fisher, yes I was actually talking with Fraser about that very point. I think I was still a bit confused by the extent of the external namespace (since I don't really use the things that will be in it myself). From the discussion, `External` seems to make sense 👍

**Comment by FraserGreenroyd** [comment]
@adecler I have removed the `GBXMLObject` entirely as it no longer is needed as it was only providing the `[XMLIgnore]` on BHoM properties which now it doesn't inherit from `BHoMObject` isn't needed.

Have kept the other bits `External` following discussion with you and comments from @al-fisher above

**Comment by adecler** [comment]
Thanks Fraser, I think the PR makes sense from a code perspective. 
Will leave to the others to make a proper review and making sure that everything still works.

**Comment by rolyhudson** [comment]
Should 'ExportDetail' and 'UnitType' also move to the Adapter as these are GBXML schema specific enums?

**Comment by FraserGreenroyd** [comment]
> Should `ExportDetail` and `UnitType` also move to the Adapter as these are GBXML schema specific enums?

No as they're used by the Config which is required by the UI for users to set up the push/pull config :smile:

**Comment by rolyhudson** [comment]
Ah yes of course 👍. These are not for serialising.

**Pull request merged**
