### PR TITLE
Migrate methods and version their move

### LINKED ISSUE #528: Move methods from XML_Engine to XML_Adapter
The following methods are suitable only for adapter operations and should be moved to reduce UI overload.

 - BH.Engine.Adapters.XML.Query.ConstructionID(Construction construction)
 - BH.Engine.Adapters.XML.Query.CADObjectID(Opening opening)
 - BH.Engine.Adapters.XML.Query.CADObjectID(Space space)

This will require versioning explaining the deletion.

This will also resolve `null` checks for these methods.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #528 

 ### Test files

 ### Changelog
 - `ConstructionID` methods moved from XML_Engine to XML_Adapter
 - `CADObjectID` methods moved from XML_Engine to XML_Adapter

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Review by akaraiskou — APPROVED** [review]

**Pull request merged**
