### PR TITLE
XML_Toolkit: Rename depth property from XMLDepth to Depth

### LINKED ISSUE #560: XML_Toolkit: Rename Bluebeam depth property
#### Description:

Bluebeam Depth is currently named 'XMLDepth' but should just be 'Depth' to align with the other parameters in the XML definition.

### PR DESCRIPTION
**Pull request by rboulton-BH**
### NOTE: Depends on 
https://github.com/BHoM/Versioning_Toolkit/pull/208

 ### Issues addressed by this PR

 Closes #560 

 
Rename Bluebeam depth property from XMLDepth to Depth

 ### Test files

Testing should be carried out using XML test procedure: https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/03_Alpha/BHoM/XML_Toolkit/XML_Toolkit_PullTest.gh?csf=1&web=1&e=BSk0dH

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
This was a deliberate decision in #555 because of the issue with having a double `Depth` to make this clear it is the XML String representation of Depth. @CKBoulter added a method to query the numerical Depth to avoid confusion.

**Comment by rboulton-BH** [comment]
Changes requested by @FraserGreenroyd have now been made and checked.

**Review by CKBoulter — APPROVED** [review]
Just tested the pull and push tests. All passed after following the procedures.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
This PR is causing a problem with versioning - @rboulton-BH let's pick up early next week to resolve - should be straight forward but I think it needs a second PR on Versioning_Toolkit to accomplish.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Review by FraserGreenroyd — APPROVED** [review]
My changes have been addressed, @CKBoulter has approved functionality.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
