### PR TITLE
Fix project compliance

### LINKED ISSUE #576: 6.2 project compliance
As noted: https://github.com/BHoM/XML_Toolkit/pull/575/checks?check_run_id=14441902834

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #576

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 14745296156

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Review by desaiwangBH — APPROVED** [review]
Compliance check passed, approving.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
