### PR TITLE
Fix UnitTypes for export to handle Imperial and SI

### LINKED ISSUE #505: XML_Toolkit: UnitType of GBXMLSettings is not working as expected
#### Description:

Found this bug in a recent project application. This setting should change the units in line 2 of the XML file generated but not functioning as expected now.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #505 

 ### Test files
See test procedure

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Review by BingWangUS — APPROVED** [review]
Tested that this fix the bug. A future review of the UnitType input is needed (#507 raised).

**Comment by FraserGreenroyd** [comment]
Thanks @BingWangUS - I have updated the test procedure for this toolkit to account for these changes :smile:

**Pull request merged**
