### PR TITLE
Remove GBXML DocumentBuilder from workflow for pushing Environment objects to XML

### LINKED ISSUE #475: add protection for Shading and unassigned Panels
image

#### Description:

Currently, node does not work without this data, it should still work

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #475 

Test files available [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FXML%5FToolkit%2F%23582%2DDocumentBuilder&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b).

I recommend pushing an Environments Model to gbXML and viewing either via [Aragog](http://www.ladybug.tools/spider/gbxml-viewer/r13/gv-app-application/gv-app.html) or another gbXML viewer of your choice.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Review by jamesramsden-bh — APPROVED** [review]
Have confirmed satisfactory behaviour by running the provided test GH file and viewing in Aragog, works as expected without issue.

**Pull request merged**
