### PR TITLE
Add pulling of Bluebeam markup schema

### LINKED ISSUE #539: XML_Toolkit: Bluebeam markup schema handling
#### Description:

Would be really useful to be have better support for the Bluebeam markup export .xml schema. Currently pulls as a functional but pretty ugly multi-nested custom object but would be better to create some sort of markup object (i don't mind if it's still just a custom object) with a series of properties & values. Note that the property names are not always consistent but the structure of the schema will always be the same.

Example schema saved here:
https://burohappold.sharepoint.com/:u:/r/sites/Direction/designtechnology/RandDWishlist/00205_Environments%20%26%20MEP/SAP%20workflow/ExampleDwelling.xml?csf=1&web=1&e=nJwf7N%5B%5D(url)

Relates to previous closed issue #537 and PR #538

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #539 

 ### Test files
See [updated test procedure](https://burohappold.sharepoint.com/:w:/r/sites/BHoM/01_Master%20File/09_QAQC/04%20-%20Testing%20Procedures/0005_Environment/0001_XML_Toolkit.docx?d=w05e62d00b2c74e24a778fbed2cf33771&csf=1&web=1&e=5NpJzM) and [associated test files](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FXML%5FToolkit&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b)

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix copyright headers ref. 4176736431

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 4176736831

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Review by emilsvedjer — APPROVED** [review]
LGTM

**Pull request merged**
