### PR TITLE
Window type

### LINKED ISSUE #175: XML_Toolkit: Add windowTypeIdRef for each GLZ element
Each solid element should use `constructionIdRef` and glazed element `windowTypeIdRef`

here is sample definition of glazed elements

At surface level
`Opening interiorShadeType="Operable" exteriorShadeType="Fixed" openingType="FixedWindow" id="aim74416" windowTypeIdRef="PwindowType-512">`

definition
 ```
 <WindowType id="PwindowType-512" DOELibIdRef="2436">
    <Name>Double Refl Tint U-SI 2.98, U-IP 0.53, SHGC 0.25, VLT 0.16</Name>
    <Description>Dbl Ref-B-H Tint 6mm/6mm Air</Description>
    <U-value unit="WPerSquareMeterK">2.98</U-value>
    <SolarHeatGainCoeff unit="Fraction">0.25</SolarHeatGainCoeff>
    <Transmittance type="Visible">0.16</Transmittance>
    <Glaze id="Glaze-L1-PwindowType-512">
      <Name>REF B TINT HI 6MM</Name>
      <Description>REF B TINT HI 6MM</Description>
      <Thickness unit="Feet">0.01969</Thickness>
      <Conductivity unit="WPerMeterK">0.9</Conductivity>
      <Transmittance type="Solar" unit="Fraction">0.15</Transmittance>
      <Transmittance type="Visible" unit="Fraction">0.18</Transmittance>
      <Transmittance type="IR" unit="Fraction">0</Transmittance>
      <Reflectance type="ExtSolar" unit="Fraction">0.09</Reflectance>
      <Reflectance type="IntSolar" unit="Fraction">0.33</Reflectance>
      <Reflectance type="ExtVisible" unit="Fraction">0.08</Reflectance>
      <Reflectance type="IntVisible" unit="Fraction">0.28</Reflectance>
      <Emittance type="ExtIR" unit="Fraction">0.84</Emittance>
      <Emittance type="IntIR" unit="Fraction">0.6</Emittance>
    </Glaze>
    <Gap id="Gas-L2-PwindowType-512">
      <Name>AIR 6MM</Name>
      <Description>Air</Description>
      <Thickness unit="Feet">0.02067</Thickness>
      <Conductivity unit="WPerMeterK">0.1</Conductivity>
    </Gap>
    <Glaze id="Glaze-L3-PwindowType-512">
      <Name>CLEAR 6MM</Name>
      <Description>CLEAR 6MM</Description>
      <Thickness unit="Feet">0.01969</Thickness>
      <Conductivity unit="WPerMeterK">0.9</Conductivity>
      <Transmittance type="Solar" unit="Fraction">0.775</Transmittance>
      <Transmittance type="Visible" unit="Fraction">0.881</Transmittance>
      <Transmittance type="IR" unit="Fraction">0</Transmittance>
      <Reflectance type="ExtSolar" unit="Fraction">0.071</Reflectance>
      <Reflectance type="IntSolar" unit="Fraction">0.071</Reflectance>
      <Reflectance type="ExtVisible" unit="Fraction">0.08</Reflectance>
      <Reflectance type="IntVisible" unit="Fraction">0.08</Reflectance>
      <Emittance type="ExtIR" unit="Fraction">0.84</Emittance>
      <Emittance type="IntIR" unit="Fraction">0.84</Emittance>
    </Glaze>
  </WindowType>

```

### LINKED ISSUE #190: XML_Toolkit: Openings Name from Revit repeats Family Type
We fix BuildingElement but missed Opening we have to do it here as well.
We have currently 
`WinInst: WinInst : SIM_EXT_GLZ`
`Skylight_ver00: Skylight_ver00 : SIM_EXT_GLZ_SKY DF01`

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #175 
Fixes #190 

Adds WindowType to schema and exports all window type constructions on default values for now.

 ### Test files
N/A

 ### Changelog
#### Added
 - Added WindowType to schema

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@michaldengusiak I have made some of the changes you have requested surrounding missing types and default descriptions.

However, I am against adding default values at this stage - particularly as one of the elements (`Conductivity`) is supplied by existing code where we already have a default in for different uses.

I feel it would be better to assign defaults to the window construction properties coming from the oM rather than in the gbXML_oM. Happy to discuss.

**Comment by michaldengusiak** [comment]
ok I am testing revit but using this branch and noticed that I can not pull anymore XML
problem with reflecting WindowType... will test on master branch now

image

**Comment by michaldengusiak** [comment]
I tested on master and works fine.. so we need to find and fix issue in this branch

**Comment by michaldengusiak** [comment]
Last test I manged to generate gbXML with GH (I need to review why Dynamois not working any more I updated latest masters) but I can see that we missing WindowType on Surface...  lets review this again
`      <Opening constructionIdRef="W105110731101151163258328373779569888495717690" openingType="FixedWindow" id="opening-7a781">`

that is why we have
```
ERROR: Reference to undeclared ID is 'W105110731101151163258328373779569888495717690'. Line Position 16 Line Number: 496

ERROR: Reference to undeclared ID is 'W105110731101151163258328373779569888495717690'. Line Position 16 Line Number: 379
```

**Pull request merged**
