### PR TITLE
Refactor out arrays

### LINKED ISSUE #495: Refactor out arrays
Related to: https://github.com/BHoM/Grasshopper_Toolkit/issues/542#issuecomment-694764533

Refactor out the arrays and the poorly constructed arrays as well!

### LINKED ISSUE #502: XML_Adapter.cs has too many attributes
The `Input` attribute which has `[Input("xmlSettings", "Input the additional XML Settings the adapter should use. Only used when pushing to an XML file. Default null")]` is no longer used and should have come out when the toolkit was refactored. This line needs deleting.

The `PreviousVersion` attribute also needs deleting.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #495 
Fixes #502 

 ### Test files
From test library

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check all

**Review by michaelhoehn — APPROVED** [review]
LGTM. Hard to argue against 10 checks. 😛

**Comment by FraserGreenroyd** [comment]
> LGTM. Hard to argue against 10 checks. 😛

Don't tempt @IsakNaslundBh - he will! 😆

**Pull request merged**
