### PR TITLE
XML_Toolkit: Pull CAD Object ID for opening if it exists

### LINKED ISSUE #290: XML_Toolkit: Pull Openings by Name
Pull openings not by openingType
`      <Opening openingType="NonSlidingDoor" id="opening-c6279">`

but by name

```
        <CADObjectId>Doors_ver01: SIM_INT_SLD [855631]</CADObjectId>
        <Name>Doors_ver01: SIM_INT_SLD</Name>
      </Opening>
```

image

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #290 

 ### Test files
Existing Pull/Push files

 ### Changelog
#### Fixed
 - Fixed pulling of CAD object ID if it exists for openings

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@michaldengusiak so what you're saying is because the file your pulling from did not contain the necessary data, the pull was unable to provide the necessary data, but when you edited the file to provide the necessary data, then the pull was able to provide it? 😖

**Comment by michaldengusiak** [comment]
in our raw gbXML file we pull..we have all data...
```
        </PlanarGeometry>
        <CADObjectId>Doors_ver01: SIM_INT_SLD [858217]</CADObjectId>
        <Name>Doors_ver01: SIM_INT_SLD</Name>
      </Opening>
```
so we pull from this gbXML above... when I push this data to new gbXML
we have this

```
        </PlanarGeometry>
        <CADObjectId> [858217]</CADObjectId>
        <Name>Doors_ver01: SIM_INT_SLD</Name>
      </Opening>
```

...so we either lose it on pull or remove it on push

**Comment by FraserGreenroyd** [comment]
You're going to need to provide that XML file so I can run some tests to try and find the code that isn't working then if that's the case cause my XML files don't produce that

**Comment by michaldengusiak** [comment]
[test file](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/XML_Toolkit/XML_Toolkit-Issue290%20PullOpening?csf=1&e=YGf3kw)

**Comment by FraserGreenroyd** [comment]
Ok this should now be fixed, test file helped :smile:

**Pull request merged**
