### PR TITLE
Add ability to handle non-schema specific XML, and push/pull standard BHoM objects in/out of XML

### LINKED ISSUE #523: Ability to push and pull generic XML schemas
Allowing for `undefined` schemas to be pushed and pulled depending on the deserialisation into custom objects (on pull) or provided schema (1 file per object) on push.

FYI: @mariatjader

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #523 

 ### Test files
[Available here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FXML%5FToolkit%2F%23524%2DGenericXML)

Test files include 2 non-BHoM XML files, one from the SAP process courtesy of @linaeriksson and one from @mariatjader .
Also included is a Grasshopper script which has some Environment Panels internalised to push to test the pull/push of BHoM objects.

 ### Changelog
 - Ability to pull and push BHoM Objects to/from XML
 - Ability to pull generic XML files into BHoM Custom Objects
 - Ability to push objects with their own XML Attributes to an XML file

### Additional comments
As the change log says, this is bringing in some great new functionality for the XML Toolkit. No more will it be shackled by the requirement to know the schema before serialising or deserialising.

There are 4 component parts which ought to be tested as part of this PR based on the features brought in, all of which are handled within the test files, but for reference are described here.

1. The ability to push BHoM Objects
You can now push any BHoM object into an adapter with an undefined schema and it will generate an XML file based on the properties of the BHoM objects. This schema is as similar to the JSON schema provided by the Serialiser_Engine as possible, because it helps with the reading in item 2.

2. The ability to pull BHoM Objects
You can now pull an XML file which comprises BHoM objects providing the XML file was generated using the XML push functionality. It will read back the base object as a Custom Object, but then all sub-objects will be correct BHoM objects.

3. The ability to pull generic XML files
This was requested by @mariatjader and @michaelhoehn as an ability to just read any XML file into BHoM Custom Objects. This works the same as the `FromJson` component which will return any JSON as Custom Objects if they're not BHoM Objects, in so much as this will return Custom Objects for an XML file that does not contain BHoM valid objects.

4. The ability to push generic XML files
Currently the schema objects need defining in the XML Toolkit to push to a specific XML schema, but that means that workflows (such as the SAP workflow that @linaeriksson is working on) can't make use of the XML Toolkit to produce XML files without passing the beta standards for inclusion of new toolkits. This is because the XML Toolkit would need to know about those oMs for conversion, which it can't do if they're not higher in the dependency chain of itself. That requires new workflow toolkits (such as SAP) to be beta ready almost immediately to utilise XML Toolkit before this PR.
This PR allows any new workflow to define their XML objects in their own toolkit (using XML attributes to decorate properties in same way that is done in XML Toolkit) and then push them to an XML file using the XML Toolkit. This should open up the possibility to demo new workflows with XML without the overhead of needing beta inclusion instantly.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Review by rolyhudson — APPROVED** [review]
Looks good to me. I have through the code and run the test files. Working as expected. 

Worth noting that when passing in a collection of objects (of different types) to push these will be processed in groups defined by object type (this behaviour is inherited from the BHoM Adapter Push method). Each group will be serialised and (over)written to the file specified. So the final final will not contain serialised versions of all objects just the last group. I understand this behaviour will be addressed in future refactoring.

Lastly, I would expect a review from someone planning to use this in a workflow to validate it from the discipline specific perspective.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Review by michaelhoehn — APPROVED** [review]
LGTM! Works well on my tests. I'm excited to put this to use in an upcoming project.

**Pull request merged**
