### PR TITLE
Add support for KML

### LINKED ISSUE #441: Add support for KML files
Would be great to extend the toolkit to support the generation of and eventually reading of KML files for use with Google Earth.
[KML documentation ](https://developers.google.com/kml/documentation/kmlreference)

I propose we focus on a specific current use case: pushing geo referenced mesh objects. 

This is part of a current workflow for modelling and stadium seating bowls. Export to KML is allowing checking against the (sometimes 3d) data in Google Earth.

Sample KML files from this workflow are available [here](https://teams.microsoft.com/_#/files/Bath%20Structures%20Team%202?threadId=19%3A32a9fe4f70e547f9b9432e57a2c81ffd%40thread.skype&ctx=channel&context=KML&rootfolder=%252Fsites%252FStructures-Bath%252FShared%2520Documents%252FBath%2520Structures%2520Team%25202%252FStadia%2520Database%252FStadia%2520models%252FKML)

Currently implemented as a simple `Convert` method using a `StringBuilder` [here](https://github.com/BuroHappoldEngineering/Buildings_Toolkit/blob/RefactoringSeatingModelling/Venue_Engine/Convert/ToKML.cs). Currently this approach is not using `XmlSerializer` but should do to integrate with XML_Toolkit..

Some other minimal requirements below.

Objects required in a KML folder in XML_oM:
- `Style`
- `Polygon`
- `Folder`

Helper method to convert geometry to Geospatial:
`NorthEastDisplacement`

Geometric inputs required to convert from model space to geospatial:
`Latitude` 
`Longitude` 
`NorthVector`
`referencePoint` (in xyz model space)

### PR DESCRIPTION
**Pull request by rolyhudson**
### Issues addressed by this PR
Fixes #441 
So far just pushing a Mesh to a KML file - the use case described in #441. So far no customisation of styles and document structure has been implemented.

But the framework is in place to extend to more of the features offered by the KML format. Would be good to discuss further to better understand other use cases @michaldengusiak.

[IMAGE ALT TEXT HERE](https://www.youtube.com/watch?v=SVCVpxp5IdU)

 ### Test files
[kmlTest.zip](https://github.com/BHoM/XML_Toolkit/files/4560216/kmlTest.zip)

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@rolyhudson is there a link to the schema for KML to validate against?

**Comment by rolyhudson** [comment]
@FraserGreenroyd  sorry should have included these:
- Full schema is: http://schemas.opengis.net/kml/
- User friendly version: https://developers.google.com/kml/documentation/kmlreference
- Good starting point for any one wanting to get involved: https://developers.google.com/kml/documentation/kml_tut

**Comment by rolyhudson** [comment]
Any thoughts on this @michaldengusiak?

**Comment by rolyhudson** [comment]
Reaching out to @jdarcyBHE and @michaelhoehn for testing and input on expected workflows / use cases for this.

**Comment by jdarcyBHE** [comment]
Trying to build the code for the XML_toolkit. Its throwing a namespace error.
> The type or namespace name 'Triangulation' does not exist in the namespace 'BH.Engine.Geometry' 
Tried to find the reference but can't seem to locate it, any thoughts?

**Comment by FraserGreenroyd** [comment]
@jdarcyBHE you will need to have the TriangleNet_Toolkit cloned and built as it provides the dependency you're looking for for XML Toolkit.

**Comment by michaldengusiak** [comment]
@rolyhudson  do you have any example for the test?

**Comment by rolyhudson** [comment]
@michaldengusiak did the file not posted above work? Should be all you need in there to run the stadium example
 ### Test files
[kmlTest.zip](https://github.com/BHoM/XML_Toolkit/files/4560216/kmlTest.zip)

**Comment by rolyhudson** [comment]
@michaldengusiak yes you need a bit of context data. Latitude and Longitude and a north vector (also altitude if using `AltitudeMode.Absolute`).
The workflow I have been using is to check Google Earth for Latitude and Longitude and Altitude:


I then reference a screen shot into my model space using Picture or PictureFrame in Rhino:

In this case the image does not align with the XY plane of my model. So the input `NorthVector` can be defined using the `Reference` (0,0,0 in this case) and a point perpendicular on the image edge.

Does that make sense?

The `Reference` can be anywhere in the model but corresponds to the reference latitude longitude.

If for some reason you don't have altitude (metres above sea-level) of your object you can try `AltitudeMode.RelativeToGround` which if google earths estimate of the ground is nice and smooth should place your model on the surface of the earth. Although in practice it is rare to have a nice smooth section of ground and the result can be a bit wobbly.

**Comment by michaldengusiak** [comment]
@rolyhudson  this is clear now, thanks a lot
how do you import the image into Rhino just print screen or export from Google to keep correct size and orientation?

**Comment by rolyhudson** [comment]
@michaldengusiak good question. In google earth you first need to make sure you have a top view by clicking on the 2d/3d icon:

Then click the compass icon to set north up:

I then just zoom to fit the area I want and take a screen shot.
In the example we have a fairly good scaling reference - the football pitch, which we can assume to be 105 x 65. So I rotate and scale the image to fit this in Rhino. If you have got the north arrow up the edge of the image will always provide a north south reference.

This allows you to model in a convenient orientation - not needing to use north up although you can do if you prefer.

If you want to understand more on how the convert from model space points to latitude, longtiude points works, have a read of [this](https://gis.stackexchange.com/a/30037) and see the BHoM implementation [here](https://github.com/BHoM/XML_Toolkit/blob/XML_Toolkit-%23441-SupportKML/XML_Adapter/Convert/KML/ToLatLon.cs).

**Comment by michaldengusiak** [comment]
@rolyhudson  perfect all clear now,

**Comment by michaelhoehn** [comment]
Hey @rolyhudson nice work! I've just pushed a few tests through and had a bit of fun 😄 Here are a few geometries I tried to push through. Apologies if I'm a bit outside of any other ongoing mesh viz discussions, but hope this feedback can be helpful! 

image

Geometries include: 
- extrusions _(solids did not work)_ 
- twisted surfaces (lofts)
- tapered surfaces
- complex meshes _(satellite did not work)_

Additional functionality tested:
- Scaling works great along with changing lat/long coordinates.
- Google earth in web browser support works great! 

Here are some additional views from within the browser: 
image

image

General feedback: 
- Would be good to test visibility settings like generic color/shading functionalities. 
- Some meshes needed to be broken down into distinct faces; the twisted tower for example needs to be pushed through as four meshes, while the simple extrusion works as a single mesh. Perhaps this is functionality/limitation of the TriangleNet engine. 
- Pushing capped or solid meshes is currently not functional, not sure the reasoning for this?

**Pull request merged**
