### PR TITLE
Upgrade XML Toolkit to NetStandard 2.0

### LINKED ISSUE #581: Upgrade to .NetStandard 2.0
In line with some other toolkits - upgrade this toolkit to NetStandard

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #581

### CODE REVIEW

**Comment by jamesramsden-bh** [comment]
@bhom check installer

**Comment by jamesramsden-bh** [comment]
@BHoMBot check installer

**Review by jamesramsden-bh — APPROVED** [review]
Installer bot check is happy, so happy to approve.

**Review by jamesramsden-bh — APPROVED** [review]
Resubmitting approval following rebase

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: installer, versioning, ready-to-merge

**Pull request merged**
