### PR TITLE
Functional tests for pushing GBXML files

### LINKED ISSUE #595: .ci functional tests for XML adapter push
#### Definition of the test :

A set of functional tests will be created that will test the XML adapter's `Push` action. These tests will replicate the tests done in the current XML toolkit push test procedure, as well as adding any other valid tests not already reflected in the test procedures.
- Test pushing GBXML
    - Test that BHoM environment objects are pushed correctly

The json test file created for issue #594 will be deserialised and used to push data to xml.

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #595 

 
Functional tests for the the pull action have been created that test a number of scenarios:
- Pushing BHoM environment objects to GBXML
    - Pushing full building
    - Pushing building shell
    - Pushing SI and non-SI units
    - Pushing with and without construction objects

 ### Test files

 ### Changelog

 ### Additional comments

Uses the JSON serialised BHoM objects to push to GBXML and compare.

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check compliance
@BHoMBot check core

**Comment by Tom-Kingstone** [comment]
@BHoMBot check unit-tests

**Comment by Tom-Kingstone** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
